services:
  nginx:
    image: nginx:alpine-slim
    working_dir: /etc/nginx/
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    command: ["nginx", "-g", "daemon off;"]
